jobs:
  include:

    - name: uasdk_default_quasar_design
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            ./quasar.py set_build_config .CI/travis/build_configs/uasdk-eval.cmake ;
            ./quasar.py build ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;"

    - name: uasdk_test_sync_methods
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            cp .CI/test_cases/test_methods/Design.xml Design ;
            ./quasar.py generate device --all ;
            ./quasar.py set_build_config .CI/travis/build_configs/uasdk-eval.cmake ;
            cp -v .CI/test_cases/test_methods/config.xml bin/ ;
            ./quasar.py build ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;"

    - name: uasdk_test_cache_variables
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            cp .CI/test_cases/test_cache_variables/Design.xml Design ;
            ./quasar.py generate device --all ;
            ./quasar.py set_build_config .CI/travis/build_configs/uasdk-eval.cmake ;
            ./quasar.py build ;
            cp .CI/test_cases/test_cache_variables/DTestClass.test.h Device/include/DTestClass.h ;
            cp .CI/test_cases/test_cache_variables/DTestClass.test.cpp Device/src/DTestClass.cpp ;
            cp -v .CI/test_cases/test_cache_variables/config.xml build/bin ;
            ./quasar.py build ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;"

    - name: uasdk_test_source_variables
      script:
        - docker run --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            cp .CI/test_cases/test_source_variables/Design.xml Design ;
            ./quasar.py generate device --all ;
            ./quasar.py set_build_config .CI/travis/build_configs/uasdk-eval.cmake ;
            cp -v .CI/test_cases/test_source_variables/config.xml bin/ ;
            ./quasar.py build ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;"

    - name: uasdk_test_config_entries
      script:
        - docker run  --interactive --tty pnikiel/quasar:quasar-uasdk /bin/bash -c "
            git clone --recursive -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} https://github.com/quasar-team/quasar.git ;
            cd quasar ;
            cp -v .CI/test_cases/test_config_entries/Design.xml Design ;
            cp -v .CI/test_cases/test_config_entries/config.xml bin/ ;
            ./quasar.py set_build_config .CI/travis/build_configs/uasdk-eval.cmake ;
            ./quasar.py build ;
            ./.CI/travis/server_fixture.py --command_to_run uasak_dump ;"
